archive:
  format: binary
  name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
builds:
  - main: ./main.go
    id: "cmd"
    binary: gon
    ldflags:
      - -X main.Version={{.Tag}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
