archives:
  - files:
    - UNLICENSE
    - README.md
    format_overrides:
    - goos: windows
      format: zip
builds:
  - main: ./main.go
    id: "cmd"
    binary: gon
    goos:
      - linux
      - windows
